# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7 triangle number would 
# be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55,...
# Let us list the factors of the first seven triangle numbers:

#  1 : 1
#  3 : 1,3
#  6 : 1,2,3,6
# {10} : 1,2,5,10
# {15} : 1,3,5,15
# {21} : 1,3,7,21
# {28} : 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

def count_divisors(number):
    '''Counts divisors of given number'''
    counter = 1
    for i in range(1,(number + 1)//2):
        if number % i == 0:
            counter += 1
    return counter

# n = 2
# number = 1
# while(True):                                                  # TOO
#     if count_divisors(number) > 500:                          # LONG       
#         print(n-1, number)
#         break
#     else:
#         number = number + n
#         n = n + 1
#         print(n+1, number)

